ALTER TABLE holder_votes ADD COLUMN IF NOT EXISTS reason TEXT NOT NULL DEFAULT '';
ALTER TABLE holder_votes ADD COLUMN IF NOT EXISTS message TEXT NOT NULL DEFAULT '';
ALTER TABLE holder_votes ADD COLUMN IF NOT EXISTS signature TEXT NOT NULL DEFAULT '';
